/*
 * VehicleService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: johnfg2610\"gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import "time"

// VehicleForm - Represents a vehicle about to be created
type VehicleForm struct {
	VehicleTypeID uint64 `json:"vehicleInformation,omitempty"`

	PlateNumber uint8 `json:"plateNumber,omitempty" gorm:"UNIQUE_INDEX"`

	Millage uint64 `json:"millage,omitempty"`

	MOTExpiry time.Time `json:"MOTExpiry,omitempty"`

	PlateExpiry time.Time `json:"plateExpiry,omitempty"`

	InsuranceExpiry time.Time `json:"insuranceExpiry,omitempty"`

	RoadTaxExpiry time.Time `json:"roadTaxExpiry,omitempty"`

	BusinessID uint64 `json:"businessID,omitempty" gorm:"INDEX"`

	DriverID uint64 `json:"driverID,omitempty"`

	IsActive bool `json:"isActive,omitempty"`

	Registration string `json:"registration,omitempty"`
}
