/*
 * VehicleService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: johnfg2610\"gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetVehicle - Get vehicle by id
func GetVehicle(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetVehicleAll - Your GET endpoint
func GetVehicleAll(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostVehicleNew - Create new vehicle
func PostVehicleNew(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
