/*
 * VehicleService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: johnfg2610\"gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// VehicleInformation - The information relevant to this specific vehicle
type VehicleInformation struct {

	Make string `json:"make,omitempty"`

	Model string `json:"model,omitempty"`

	Color string `json:"color,omitempty"`

	YearOfManufacture int32 `json:"yearOfManufacture,omitempty"`

	PassengerSize int32 `json:"passengerSize,omitempty"`

	CO2Emissions float32 `json:"CO2Emissions,omitempty"`

	Registration string `json:"registration,omitempty"`
}
