/*
 * VehicleService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: johnfg2610\"gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// VehicleForm - Represents a vehicle about to be created
type VehicleForm struct {

	PlateNumber int32 `json:"plateNumber,omitempty"`

	Millage int32 `json:"millage,omitempty"`

	VehicleExpiry VehicleExpiry `json:"vehicleExpiry,omitempty"`

	CreationDate string `json:"creationDate,omitempty"`

	VehicleInformation VehicleInformation `json:"vehicleInformation,omitempty"`

	DriverID string `json:"driverID,omitempty"`
}
