/*
 * VehicleService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Contact: johnfg2610\"gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VehicleExpiry struct {

	MOTExpiry string `json:"MOTExpiry,omitempty"`

	PlateExpiry string `json:"plateExpiry,omitempty"`

	InsuranceExpiry string `json:"insuranceExpiry,omitempty"`

	RoadTaxExpiry string `json:"roadTaxExpiry,omitempty"`
}
